<a href="https://colab.research.google.com/github/Lotus-owl/kdta_ROS2/blob/main/perceptronTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 선형 분류


In [ ]:
def AND_gate(x1, x2):
    w1=0.5
    w2=0.5
    b=-0.7
    result = x1*w1 + x2*w2 + b
    if result <= 0:
        return 0
    else:
        return 1


In [ ]:
AND_gate(0, 0), AND_gate(0, 1), AND_gate(1, 0), AND_gate(1, 1)

(0, 0, 0, 1)

In [ ]:
def NAND_gate(x1, x2):
    w1=-0.5
    w2=-0.5
    b=0.7
    result = x1*w1 + x2*w2 + b
    if result <= 0:
        return 0
    else:
        return 1

In [ ]:
NAND_gate(0, 0), NAND_gate(0, 1), NAND_gate(1, 0), NAND_gate(1, 1)

(1, 1, 1, 0)

In [ ]:
def OR_gate(x1, x2):
    w1=0.6
    w2=0.6
    b=-0.5
    result = x1*w1 + x2*w2 + b
    if result <= 0:
        return 0
    else:
        return 1

In [ ]:
OR_gate(0, 0), OR_gate(0, 1), OR_gate(1, 0), OR_gate(1, 1)

(0, 1, 1, 1)

## 단층 퍼셉트론

In [ ]:
import torch
import torch.nn as nn

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [ ]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [ ]:
linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid).to(device)


In [ ]:
# 비용 함수와 옵티마이저 정의
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)


In [ ]:
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)

    # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 100 == 0: # 100번째 에포크마다 비용 출력
        print(step, cost.item())


0 0.7273973822593689
100 0.6931476593017578
200 0.6931471824645996
300 0.6931471824645996
400 0.6931471824645996
500 0.6931471824645996
600 0.6931471824645996
700 0.6931471824645996
800 0.6931471824645996
900 0.6931471824645996
1000 0.6931471824645996
1100 0.6931471824645996
1200 0.6931471824645996
1300 0.6931471824645996
1400 0.6931471824645996
1500 0.6931471824645996
1600 0.6931471824645996
1700 0.6931471824645996
1800 0.6931471824645996
1900 0.6931471824645996
2000 0.6931471824645996
2100 0.6931471824645996
2200 0.6931471824645996
2300 0.6931471824645996
2400 0.6931471824645996
2500 0.6931471824645996
2600 0.6931471824645996
2700 0.6931471824645996
2800 0.6931471824645996
2900 0.6931471824645996
3000 0.6931471824645996
3100 0.6931471824645996
3200 0.6931471824645996
3300 0.6931471824645996
3400 0.6931471824645996
3500 0.6931471824645996
3600 0.6931471824645996
3700 0.6931471824645996
3800 0.6931471824645996
3900 0.6931471824645996
4000 0.6931471824645996
4100 0.6931471824645996
4200

In [ ]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('모델의 출력값(Hypothesis): ', hypothesis.detach().cpu().numpy())
    print('모델의 예측값(Predicted): ', predicted.detach().cpu().numpy())
    print('실제값(Y): ', Y.cpu().numpy())
    print('정확도(Accuracy): ', accuracy.item())


모델의 출력값(Hypothesis):  [[0.5]
 [0.5]
 [0.5]
 [0.5]]
모델의 예측값(Predicted):  [[0.]
 [0.]
 [0.]
 [0.]]
실제값(Y):  [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy):  0.5


## 다층 퍼셉트론


In [ ]:
linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()
model = nn.Sequential(
          nn.Linear(2, 10, bias=True), # input_layer = 2, hidden_layer1 = 10
          nn.Sigmoid(),
          nn.Linear(10, 10, bias=True), # hidden_layer1 = 10, hidden_layer2 = 10
          nn.Sigmoid(),
          nn.Linear(10, 10, bias=True), # hidden_layer2 = 10, hidden_layer3 = 10
          nn.Sigmoid(),
          nn.Linear(10, 1, bias=True), # hidden_layer3 = 10, output_layer = 1
          nn.Sigmoid()
          ).to(device)


In [ ]:
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)  # modified learning rate from 0.1 to 1


In [ ]:
for epoch in range(10001):
    optimizer.zero_grad()
    # forward 연산
    hypothesis = model(X)

    # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    # 100의 배수에 해당되는 에포크마다 비용을 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())


0 0.6978083848953247
100 0.693110466003418
200 0.6931020021438599
300 0.6930921673774719
400 0.6930808424949646
500 0.6930676698684692
600 0.6930519938468933
700 0.6930330395698547
800 0.6930098533630371
900 0.6929808855056763
1000 0.6929439902305603
1100 0.6928958296775818
1200 0.6928311586380005
1300 0.6927415132522583
1400 0.6926121115684509
1500 0.692415714263916
1600 0.6920979619026184
1700 0.6915386915206909
1800 0.6904336214065552
1900 0.6878381371498108
2000 0.6797102689743042
2100 0.6408315300941467
2200 0.5488753914833069
2300 0.5083183646202087
2400 0.48752066493034363
2500 0.49485543370246887
2600 0.020168201997876167
2700 0.007714718580245972
2800 0.004507092759013176
2900 0.0031063624192029238
3000 0.0023384764790534973
3100 0.0018596602603793144
3200 0.0015350301982834935
3300 0.0013017852324992418
3400 0.001126720104366541
3500 0.0009909045184031129
3600 0.0008827366982586682
3700 0.0007946990663185716
3800 0.0007217366364784539
3900 0.0006604286027140915
4000 0.0006082

In [ ]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('모델의 출력값(Hypothesis): \n', hypothesis.detach().cpu().numpy())
    print('모델의 예측값(Predicted): \n', predicted.detach().cpu().numpy())
    print('실제값(Y): \n', Y.cpu().numpy())
    print('정확도(Accuracy): \n', accuracy.item())


모델의 출력값(Hypothesis): 
 [[7.4388765e-05]
 [9.9988055e-01]
 [9.9990404e-01]
 [8.8289198e-05]]
모델의 예측값(Predicted): 
 [[0.]
 [1.]
 [1.]
 [0.]]
실제값(Y): 
 [[0.]
 [1.]
 [1.]
 [0.]]
정확도(Accuracy): 
 1.0


## 미니배치와 데이터 로더

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [ ]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더


In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


In [ ]:
dataset = TensorDataset(x_train, y_train)


In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)


In [ ]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)


In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))


Epoch    0/20 Batch 1/3 Cost: 37679.203125
Epoch    0/20 Batch 2/3 Cost: 15319.972656
Epoch    0/20 Batch 3/3 Cost: 6793.727539
Epoch    1/20 Batch 1/3 Cost: 1006.436768
Epoch    1/20 Batch 2/3 Cost: 298.321472
Epoch    1/20 Batch 3/3 Cost: 73.912346
Epoch    2/20 Batch 1/3 Cost: 39.420811
Epoch    2/20 Batch 2/3 Cost: 20.900702
Epoch    2/20 Batch 3/3 Cost: 2.589400
Epoch    3/20 Batch 1/3 Cost: 2.112917
Epoch    3/20 Batch 2/3 Cost: 10.984287
Epoch    3/20 Batch 3/3 Cost: 9.822260
Epoch    4/20 Batch 1/3 Cost: 2.955473
Epoch    4/20 Batch 2/3 Cost: 9.474287
Epoch    4/20 Batch 3/3 Cost: 5.426064
Epoch    5/20 Batch 1/3 Cost: 6.313222
Epoch    5/20 Batch 2/3 Cost: 4.491042
Epoch    5/20 Batch 3/3 Cost: 11.024273
Epoch    6/20 Batch 1/3 Cost: 2.676070
Epoch    6/20 Batch 2/3 Cost: 18.070728
Epoch    6/20 Batch 3/3 Cost: 0.804834
Epoch    7/20 Batch 1/3 Cost: 1.265853
Epoch    7/20 Batch 2/3 Cost: 8.771469
Epoch    7/20 Batch 3/3 Cost: 9.976078
Epoch    8/20 Batch 1/3 Cost: 5.923325
Epo